services: 
"  - type: web" 
"    name: motobike-bot" 
"    env: python" 
"    buildCommand: pip install -r requirements.txt" 
"    startCommand: cd /opt/render/project && python main.py" 
"    envVars:" 
"      - key: BOT_TOKEN" 
"        sync: false" 
"      - key: ADMIN_ID" 
"        sync: false" 
"      - key: PORT" 
"        value: 8080" 
"      - key: RENDER" 
"        value: true" 
"    healthCheckPath: /ping" 
"    autoDeploy: true" 
